### PR TITLE
Various fixes for Magento 1.7.2

### PR DESCRIPTION
**Pull request by lejoko**
Since this extension seems not to be really maintained anymore, I sent this pull request only to help other developers find 1.7 fixes more easily...

It's mostly based on other people's work and on resyncing with Magento 1.7's codebase.

### CODE REVIEW

**Comment by toasty** [comment]
Awesome stuff, much appreciated!  And apologies for the lack of maintenance in general.
This may well be the kick I need to bring it up to speed with 1.7 'officially'.

Do you find it's generally pretty stable and bug-free with these patches or is there still quite a bit to do on top?

**Comment by lejoko** [comment]
Currently, for my own use and with these updates, I find it pretty stable. However, the website on which I use it is still under development and won't go to production before end of july (2012) at best.

I would add that I already noticed a few places in the code that look like they would fail if I'd use them. In particular the JS in app/design/frontend/base/default/template/catalog/product/view/scpoptions.phtml that I've already updated for text options might need updates for the other kinds of option fields.

Anyway, should I find other bugs, I'll continue to update my fork and this pull request at least until the site opens.

**Comment by mylesagray** [comment]
Works like a charm on 1.7.2 here - used in conjunction with MagMi - this should be merged with master.

**Comment by lejoko** [comment]
@toasty: the website I'm using it on is going to production in a couple of days. After much testing, and a few more bug fixes, I consider now that the plugin is pretty much stable. For my own use it's fully production ready. I use most of the Ajax features, on products with text options and group prices. The only downside is that some of the changes I made are probably only compatible with Magento 1.7+ (in particular: the way resource models are declared changed in 1.7 and adjustments were required in this area for the indexing to work).

So I'd say: please pull!

**Pull request closed without merging**
